import { criarIndicadorSituacao } from '../../../componentes/indicador-situacao/indicador-situacao';
import type { Kit } from '../../../modelos/kit';
import { buscarPatrulhaPorId } from '../../../repositorios/repositorio-patrulhas';
import { buscarSecaoPorId } from '../../../repositorios/repositorio-secoes';
import { listarKits } from '../../../repositorios/repositorio-kits';
import { calcularResumoKit } from '../../../servicos/servico-kits';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { normalizarTexto } from '../../../utilitarios/normalizador-texto';
import { textoSituacao } from '../../../utilitarios/criador-html';

function criarCartao(kit: Kit): HTMLElement { const resumo = calcularResumoKit(kit); const artigo = document.createElement('article'); artigo.className = 'kits-listagem__cartao'; const topo = document.createElement('header'); const titulo = document.createElement('h3'); titulo.className = 'kits-listagem__nome'; titulo.textContent = kit.nome; const tipo = document.createElement('small'); tipo.className = 'kits-listagem__tipo'; tipo.textContent = textoSituacao(kit.tipo); titulo.append(tipo); topo.append(titulo, criarIndicadorSituacao(resumo.completo ? kit.situacao : 'incompleto')); const barra = document.createElement('div'); barra.className = 'kits-listagem__progresso'; barra.setAttribute('aria-label', `${resumo.percentual}% completo`); const preenchimento = document.createElement('span'); preenchimento.style.width = `${resumo.percentual}%`; barra.append(preenchimento); const dados = document.createElement('div'); dados.className = 'kits-listagem__dados'; const itens = document.createElement('span'); itens.textContent = `${resumo.quantidadeItens} item(ns)`; const completude = document.createElement('span'); completude.textContent = `${resumo.percentual}% completo`; const vinculo = document.createElement('span'); vinculo.textContent = buscarPatrulhaPorId(kit.patrulhaId)?.nome ?? buscarSecaoPorId(kit.secaoId)?.nome ?? 'Uso geral'; dados.append(itens, completude, vinculo); const acoes = document.createElement('footer'); acoes.className = 'kits-listagem__acoes'; const ver = document.createElement('a'); ver.href = `../kit-detalhes/index.html?id=${encodeURIComponent(kit.id)}`; ver.textContent = 'Visualizar'; const editar = document.createElement('a'); editar.href = `../kit-formulario/index.html?id=${encodeURIComponent(kit.id)}`; editar.textContent = 'Editar'; acoes.append(ver, editar); artigo.append(topo, barra, dados, acoes); return artigo; }
function renderizarLista(): void { const termo = normalizarTexto(document.querySelector<HTMLInputElement>('#filtro-pesquisa')?.value ?? ''); const tipo = document.querySelector<HTMLSelectElement>('#filtro-tipo')?.value ?? ''; const kits = listarKits().filter((kit) => normalizarTexto(kit.nome).includes(termo) && (!tipo || kit.tipo === tipo)); const lista = document.querySelector<HTMLElement>('#lista-kits'); lista?.replaceChildren(); if (kits.length === 0) { const vazio = document.createElement('p'); vazio.className = 'kits-listagem__vazio'; vazio.textContent = 'Nenhum kit encontrado. Crie o primeiro kit de campo do grupo.'; lista?.append(vazio); } else kits.forEach((kit) => lista?.append(criarCartao(kit))); const resumo = document.querySelector<HTMLElement>('#resumo-kits'); if (resumo) resumo.textContent = `${kits.length} kit(s) encontrado(s).`; }
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Kits de Campo')) return; document.querySelector('#filtro-pesquisa')?.addEventListener('input', renderizarLista); document.querySelector('#filtro-tipo')?.addEventListener('change', renderizarLista); renderizarLista(); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
