import { mostrarMensagem } from '../../../componentes/mensagem-retorno/mensagem-retorno';
import type { Atividade, TipoAtividade } from '../../../modelos/atividade';
import type { ItemAtividade } from '../../../modelos/item-atividade';
import { adicionarAtividade, atualizarAtividade, buscarAtividadePorId, listarItensDaAtividade, salvarItensDaAtividade } from '../../../repositorios/repositorio-atividades';
import { buscarKitPorId, listarKits } from '../../../repositorios/repositorio-kits';
import { buscarMaterialPorId, listarMateriais } from '../../../repositorios/repositorio-materiais';
import { listarSecoes } from '../../../repositorios/repositorio-secoes';
import { listarUsuarios } from '../../../repositorios/repositorio-usuarios';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { dataLocalParaIso, isoParaCampoData } from '../../../utilitarios/formatador-data';
import { gerarIdentificador } from '../../../utilitarios/gerador-identificador';
import { obterParametro } from '../../../utilitarios/manipulador-url';

function campo<T extends HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id: string): T | null { return document.querySelector<T>(`#${id}`); }
function valor(id: string): string { return campo<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id)?.value ?? ''; }
function definirErro(id: string, mensagem: string): void { const elemento = document.querySelector<HTMLElement>(`#${id}`); if (elemento) elemento.textContent = mensagem; }
let atividadeEmEdicao: Atividade | null = null; let itens: ItemAtividade[] = [];

function preencherCarga(): void {
  const selecao = campo<HTMLSelectElement>('campo-carga'); if (!selecao) return; selecao.replaceChildren(); const vazia = document.createElement('option'); vazia.value = ''; vazia.textContent = 'Selecione'; selecao.append(vazia);
  if (valor('campo-tipo-carga') === 'kit') listarKits().forEach((kit) => { const opcao = document.createElement('option'); opcao.value = kit.id; opcao.textContent = kit.nome; selecao.append(opcao); });
  else listarMateriais().filter((material) => material.estado !== 'baixado').forEach((material) => { const opcao = document.createElement('option'); opcao.value = material.id; opcao.textContent = material.nome; selecao.append(opcao); });
}
function nomeItem(item: ItemAtividade): string { if (item.materialId) return buscarMaterialPorId(item.materialId)?.nome ?? 'Material não encontrado'; return buscarKitPorId(item.kitId ?? '')?.nome ?? 'Kit não encontrado'; }
function renderizarItens(): void {
  const lista = document.querySelector<HTMLElement>('#lista-carga'); lista?.replaceChildren(); itens.forEach((item) => { const linha = document.createElement('article'); linha.className = 'atividade-formulario__item'; const nome = document.createElement('span'); nome.textContent = `${item.kitId ? 'Kit: ' : 'Material: '}${nomeItem(item)}`; const quantidade = document.createElement('input'); quantidade.type = 'number'; quantidade.min = '1'; quantidade.step = '1'; quantidade.value = String(item.quantidadeSolicitada); quantidade.setAttribute('aria-label', `Quantidade de ${nomeItem(item)}`); quantidade.addEventListener('change', () => item.quantidadeSolicitada = Math.max(1, Number(quantidade.value) || 1)); const remover = document.createElement('button'); remover.type = 'button'; remover.textContent = '×'; remover.setAttribute('aria-label', `Remover ${nomeItem(item)}`); remover.addEventListener('click', () => { itens = itens.filter((atual) => atual.id !== item.id); renderizarItens(); }); linha.append(nome, quantidade, remover); lista?.append(linha); });
}
function adicionarCarga(): void {
  const referenciaId = valor('campo-carga'); const quantidade = Number(valor('campo-quantidade')); const eKit = valor('campo-tipo-carga') === 'kit'; if (!referenciaId || !Number.isFinite(quantidade) || quantidade <= 0) { definirErro('erro-carga', 'Selecione um material ou kit e informe uma quantidade maior que zero.'); return; }
  const existente = itens.find((item) => eKit ? item.kitId === referenciaId : item.materialId === referenciaId); if (existente) { existente.quantidadeSolicitada = quantidade; mostrarMensagem('Quantidade do item atualizada.', 'informacao'); } else itens.push({ id: gerarIdentificador('item-atividade'), atividadeId: atividadeEmEdicao?.id ?? '', materialId: eKit ? null : referenciaId, kitId: eKit ? referenciaId : null, quantidadeSolicitada: quantidade, quantidadeRetirada: 0, quantidadeDevolvida: 0, situacao: 'planejado' }); definirErro('erro-carga', ''); renderizarItens();
}
function validarFormulario(): boolean {
  definirErro('erro-nome', valor('campo-nome').trim() ? '' : 'Informe o nome.'); definirErro('erro-saida', valor('campo-saida') ? '' : 'Informe a data de saída.'); definirErro('erro-retorno', valor('campo-retorno') ? '' : 'Informe a data de retorno.'); if (valor('campo-saida') && valor('campo-retorno') && valor('campo-retorno') < valor('campo-saida')) definirErro('erro-retorno', 'O retorno não pode ser anterior à saída.'); definirErro('erro-secao', valor('campo-secao') ? '' : 'Selecione a seção.');
  const responsavel = listarUsuarios().find((usuario) => usuario.id === valor('campo-responsavel')); definirErro('erro-responsavel', responsavel?.perfil === 'escotista' && responsavel.situacao === 'ativo' ? '' : 'Selecione um escotista ativo.'); const jovens = Number(valor('campo-jovens')); const adultos = Number(valor('campo-adultos')); definirErro('erro-participantes', Number.isFinite(jovens) && jovens >= 0 && Number.isFinite(adultos) && adultos >= 0 ? '' : 'As quantidades não podem ser negativas.');
  return !['erro-nome', 'erro-saida', 'erro-retorno', 'erro-secao', 'erro-responsavel', 'erro-participantes'].some((id) => document.querySelector(`#${id}`)?.textContent);
}
function salvarAtividade(evento: Event): void {
  evento.preventDefault(); if (!validarFormulario()) { definirErro('erro-geral', 'Corrija os campos indicados.'); return; } const id = atividadeEmEdicao?.id ?? gerarIdentificador('atividade'); const atividade: Atividade = { id, nome: valor('campo-nome').trim(), tipo: valor('campo-tipo') as TipoAtividade, local: valor('campo-local').trim(), dataSaida: dataLocalParaIso(valor('campo-saida')), dataRetorno: dataLocalParaIso(valor('campo-retorno')), secaoId: valor('campo-secao'), quantidadeJovens: Number(valor('campo-jovens')), quantidadeAdultos: Number(valor('campo-adultos')), responsavelId: valor('campo-responsavel'), situacao: atividadeEmEdicao?.situacao ?? 'planejamento', observacoes: valor('campo-observacoes').trim(), dataCadastro: atividadeEmEdicao?.dataCadastro ?? new Date().toISOString() }; if (atividadeEmEdicao) atualizarAtividade(atividade); else adicionarAtividade(atividade); salvarItensDaAtividade(id, itens.map((item) => ({ ...item, atividadeId: id }))); window.location.href = `../atividade-detalhes/index.html?id=${encodeURIComponent(id)}&salvo=1`;
}
function preencherSelecoes(): void { listarSecoes().filter((secao) => secao.situacao === 'ativa').forEach((secao) => { const opcao = document.createElement('option'); opcao.value = secao.id; opcao.textContent = secao.nome; campo<HTMLSelectElement>('campo-secao')?.append(opcao); }); listarUsuarios().filter((usuario) => usuario.perfil === 'escotista' && usuario.situacao === 'ativo').forEach((usuario) => { const opcao = document.createElement('option'); opcao.value = usuario.id; opcao.textContent = usuario.nomeCompleto; campo<HTMLSelectElement>('campo-responsavel')?.append(opcao); }); }
function carregarEdicao(): void { const id = obterParametro('id'); if (!id) return; atividadeEmEdicao = buscarAtividadePorId(id); if (!atividadeEmEdicao) { definirErro('erro-geral', 'Atividade não encontrada.'); return; } const titulo = document.querySelector<HTMLElement>('#titulo-formulario'); if (titulo) titulo.textContent = 'Editar atividade'; const valores: Array<[string, string]> = [['campo-nome', atividadeEmEdicao.nome], ['campo-tipo', atividadeEmEdicao.tipo], ['campo-local', atividadeEmEdicao.local], ['campo-saida', isoParaCampoData(atividadeEmEdicao.dataSaida)], ['campo-retorno', isoParaCampoData(atividadeEmEdicao.dataRetorno)], ['campo-secao', atividadeEmEdicao.secaoId], ['campo-responsavel', atividadeEmEdicao.responsavelId], ['campo-jovens', String(atividadeEmEdicao.quantidadeJovens)], ['campo-adultos', String(atividadeEmEdicao.quantidadeAdultos)], ['campo-observacoes', atividadeEmEdicao.observacoes]]; valores.forEach(([idCampo, conteudo]) => { const elemento = campo<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(idCampo); if (elemento) elemento.value = conteudo; }); itens = listarItensDaAtividade(id); }
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Cadastro de Atividade')) return; preencherSelecoes(); carregarEdicao(); preencherCarga(); renderizarItens(); campo<HTMLSelectElement>('campo-tipo-carga')?.addEventListener('change', preencherCarga); document.querySelector('#botao-adicionar-carga')?.addEventListener('click', adicionarCarga); document.querySelector('#formulario-atividade')?.addEventListener('submit', salvarAtividade); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
