import type { ComponenteMaterial } from '../../../modelos/componente-material';
import type { EstadoMaterial, Material, OrigemMaterial, TipoMaterial } from '../../../modelos/material';
import { listarCategorias } from '../../../repositorios/repositorio-categorias';
import { listarComponentesPorMaterial, salvarComponentesDoMaterial } from '../../../repositorios/repositorio-componentes';
import { listarLocalizacoes } from '../../../repositorios/repositorio-localizacoes';
import { adicionarMaterial, atualizarMaterial, buscarMaterialPorId, listarMateriais } from '../../../repositorios/repositorio-materiais';
import { listarSecoes } from '../../../repositorios/repositorio-secoes';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { dataLocalParaIso, isoParaCampoData } from '../../../utilitarios/formatador-data';
import { gerarIdentificador } from '../../../utilitarios/gerador-identificador';
import { obterParametro } from '../../../utilitarios/manipulador-url';

const nomesComponentes = ['Sobreteto', 'Varetas', 'Estacas', 'Cordas', 'Bolsa de transporte'];
let materialEmEdicao: Material | null = null;

function campo<T extends HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id: string): T | null { return document.querySelector<T>(`#${id}`); }
function valor(id: string): string { return campo<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id)?.value ?? ''; }
function numero(id: string): number { const conteudo = valor(id); return conteudo === '' ? 0 : Number(conteudo); }
function numeroOpcional(id: string): number | null { const conteudo = valor(id); return conteudo === '' ? null : Number(conteudo); }
function definirErro(id: string, mensagem: string): void { const elemento = document.querySelector<HTMLElement>(`#${id}`); if (elemento) elemento.textContent = mensagem; }
function preencherSelecao(id: string, valores: Array<{ id: string; nome: string }>): void { const selecao = campo<HTMLSelectElement>(id); valores.forEach((registro) => { const opcao = document.createElement('option'); opcao.value = registro.id; opcao.textContent = registro.nome; selecao?.append(opcao); }); }
function categoriaSelecionada(): string { return listarCategorias().find((categoria) => categoria.id === valor('campo-categoria'))?.nome.toLocaleLowerCase('pt-BR') ?? ''; }
function atualizarCamposCondicionais(): void {
  const categoria = categoriaSelecionada(); const barraca = categoria.includes('barraca'); const corda = categoria.includes('corda'); const ferramenta = categoria.includes('ferramenta');
  const grupos: Array<[string, boolean]> = [['grupo-capacidade', barraca], ['grupo-controla-componentes', barraca], ['grupo-comprimento', corda], ['grupo-restricao', ferramenta]]; grupos.forEach(([id, visivel]) => { const elemento = document.querySelector<HTMLElement>(`#${id}`); if (elemento) elemento.hidden = !visivel; }); atualizarSecaoComponentes();
}
function atualizarSecaoComponentes(): void { const secao = document.querySelector<HTMLElement>('#secao-componentes'); const controla = campo<HTMLInputElement>('campo-controla-componentes')?.checked ?? false; if (secao) secao.hidden = !(categoriaSelecionada().includes('barraca') && controla); }
function renderizarComponentes(componentes: ComponenteMaterial[] = []): void {
  const lista = document.querySelector<HTMLElement>('#lista-componentes'); if (!lista) return; lista.replaceChildren();
  nomesComponentes.forEach((nome, indice) => { const salvo = componentes.find((componente) => componente.nome === nome); const linha = document.createElement('div'); linha.className = 'material-formulario__componente'; const titulo = document.createElement('strong'); titulo.textContent = nome; const quantidade = document.createElement('label'); quantidade.textContent = 'Quantidade encontrada'; const input = document.createElement('input'); input.type = 'number'; input.min = '0'; input.step = '1'; input.value = String(salvo?.quantidadeEncontrada ?? 0); input.dataset.componenteQuantidade = String(indice); quantidade.append(input); const estado = document.createElement('label'); estado.textContent = 'Estado'; const selecao = document.createElement('select'); selecao.dataset.componenteEstado = String(indice); ['bom', 'ausente', 'danificado'].forEach((estadoValor) => { const opcao = document.createElement('option'); opcao.value = estadoValor; opcao.textContent = estadoValor === 'bom' ? 'Bom' : estadoValor === 'ausente' ? 'Ausente' : 'Danificado'; opcao.selected = (salvo?.estado ?? 'bom') === estadoValor; selecao.append(opcao); }); estado.append(selecao); linha.append(titulo, quantidade, estado); lista.append(linha); });
}
function validarFormulario(): boolean {
  definirErro('erro-nome', valor('campo-nome').trim() ? '' : 'Informe o nome.'); definirErro('erro-categoria', valor('campo-categoria') ? '' : 'Selecione a categoria.'); definirErro('erro-localizacao', valor('campo-localizacao') ? '' : 'Selecione a localização.'); definirErro('erro-unidade', valor('campo-unidade').trim() ? '' : 'Informe a unidade.');
  definirErro('erro-quantidade', Number.isFinite(numero('campo-quantidade-total')) && numero('campo-quantidade-total') >= 0 ? '' : 'A quantidade não pode ser negativa.'); definirErro('erro-quantidade-minima', Number.isFinite(numero('campo-quantidade-minima')) && numero('campo-quantidade-minima') >= 0 ? '' : 'A quantidade mínima não pode ser negativa.');
  const codigoDuplicado = valor('campo-codigo').trim() && listarMateriais().some((material) => material.codigoPatrimonio.toLocaleLowerCase('pt-BR') === valor('campo-codigo').trim().toLocaleLowerCase('pt-BR') && material.id !== materialEmEdicao?.id); definirErro('erro-codigo', codigoDuplicado ? 'Este código de patrimônio já está cadastrado.' : '');
  const valorUnitario = numeroOpcional('campo-valor'); definirErro('erro-valor', valorUnitario === null || (Number.isFinite(valorUnitario) && valorUnitario >= 0) ? '' : 'Informe um valor válido.');
  return !['erro-nome', 'erro-categoria', 'erro-localizacao', 'erro-unidade', 'erro-quantidade', 'erro-quantidade-minima', 'erro-codigo', 'erro-valor'].some((id) => document.querySelector(`#${id}`)?.textContent);
}
function obterComponentes(materialId: string, quantidadeTotal: number): ComponenteMaterial[] {
  if (!(campo<HTMLInputElement>('campo-controla-componentes')?.checked ?? false)) return [];
  return nomesComponentes.map((nome, indice) => { const quantidadeEncontrada = Number(document.querySelector<HTMLInputElement>(`[data-componente-quantidade="${indice}"]`)?.value ?? 0); const estado = document.querySelector<HTMLSelectElement>(`[data-componente-estado="${indice}"]`)?.value ?? 'bom'; return { id: listarComponentesPorMaterial(materialId).find((componente) => componente.nome === nome)?.id ?? gerarIdentificador('componente'), materialId, nome, quantidadeEsperada: quantidadeTotal, quantidadeEncontrada: Math.max(0, quantidadeEncontrada), estado: estado as ComponenteMaterial['estado'], observacoes: '' }; });
}
function salvarMaterial(evento: Event): void {
  evento.preventDefault(); if (!validarFormulario()) { definirErro('erro-geral', 'Corrija os campos indicados.'); return; } const id = materialEmEdicao?.id ?? gerarIdentificador('material'); const controla = campo<HTMLInputElement>('campo-controla-componentes')?.checked ?? false;
  const material: Material = { id, codigoPatrimonio: valor('campo-codigo').trim(), nome: valor('campo-nome').trim(), descricao: valor('campo-descricao').trim(), tipo: valor('campo-tipo') as TipoMaterial, categoriaId: valor('campo-categoria'), secaoId: valor('campo-secao') || null, localizacaoId: valor('campo-localizacao'), quantidadeTotal: numero('campo-quantidade-total'), quantidadeMinimaDesejada: numero('campo-quantidade-minima'), unidadeMedida: valor('campo-unidade').trim(), estado: valor('campo-estado') as EstadoMaterial, origem: valor('campo-origem') as OrigemMaterial, valorUnitario: numeroOpcional('campo-valor'), dataAquisicao: valor('campo-data-aquisicao') ? dataLocalParaIso(valor('campo-data-aquisicao')) : null, controlaComponentes: controla, capacidadePessoas: categoriaSelecionada().includes('barraca') ? numeroOpcional('campo-capacidade') : null, comprimentoMetros: categoriaSelecionada().includes('corda') ? numeroOpcional('campo-comprimento') : null, restricaoUso: categoriaSelecionada().includes('ferramenta') ? valor('campo-restricao').trim() || null : null, observacoes: valor('campo-observacoes').trim(), caminhoImagem: materialEmEdicao?.caminhoImagem ?? null, dataCadastro: materialEmEdicao?.dataCadastro ?? new Date().toISOString() };
  if (materialEmEdicao) atualizarMaterial(material); else adicionarMaterial(material); salvarComponentesDoMaterial(id, obterComponentes(id, material.quantidadeTotal)); window.location.href = `../material-detalhes/index.html?id=${encodeURIComponent(id)}&salvo=1`;
}
function carregarEdicao(): void {
  const id = obterParametro('id'); if (!id) { const nomeInicial = obterParametro('nome'); const campoNome = campo<HTMLInputElement>('campo-nome'); if (campoNome && nomeInicial) campoNome.value = nomeInicial; renderizarComponentes(); return; } materialEmEdicao = buscarMaterialPorId(id); if (!materialEmEdicao) { definirErro('erro-geral', 'Registro não encontrado.'); renderizarComponentes(); return; } const titulo = document.querySelector<HTMLElement>('#titulo-formulario'); if (titulo) titulo.textContent = 'Editar material';
  const valores: Array<[string, string]> = [['campo-codigo', materialEmEdicao.codigoPatrimonio], ['campo-nome', materialEmEdicao.nome], ['campo-descricao', materialEmEdicao.descricao], ['campo-tipo', materialEmEdicao.tipo], ['campo-categoria', materialEmEdicao.categoriaId], ['campo-secao', materialEmEdicao.secaoId ?? ''], ['campo-quantidade-total', String(materialEmEdicao.quantidadeTotal)], ['campo-quantidade-minima', String(materialEmEdicao.quantidadeMinimaDesejada)], ['campo-unidade', materialEmEdicao.unidadeMedida], ['campo-localizacao', materialEmEdicao.localizacaoId], ['campo-estado', materialEmEdicao.estado], ['campo-origem', materialEmEdicao.origem], ['campo-valor', materialEmEdicao.valorUnitario === null ? '' : String(materialEmEdicao.valorUnitario)], ['campo-data-aquisicao', isoParaCampoData(materialEmEdicao.dataAquisicao)], ['campo-capacidade', materialEmEdicao.capacidadePessoas === null ? '' : String(materialEmEdicao.capacidadePessoas)], ['campo-comprimento', materialEmEdicao.comprimentoMetros === null ? '' : String(materialEmEdicao.comprimentoMetros)], ['campo-restricao', materialEmEdicao.restricaoUso ?? ''], ['campo-observacoes', materialEmEdicao.observacoes]]; valores.forEach(([idCampo, conteudo]) => { const elemento = campo<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(idCampo); if (elemento) elemento.value = conteudo; }); const controle = campo<HTMLInputElement>('campo-controla-componentes'); if (controle) controle.checked = materialEmEdicao.controlaComponentes; renderizarComponentes(listarComponentesPorMaterial(materialEmEdicao.id)); atualizarCamposCondicionais();
}
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Cadastro de Material')) return; preencherSelecao('campo-categoria', listarCategorias()); preencherSelecao('campo-secao', listarSecoes()); preencherSelecao('campo-localizacao', listarLocalizacoes()); carregarEdicao(); campo<HTMLSelectElement>('campo-categoria')?.addEventListener('change', atualizarCamposCondicionais); campo<HTMLInputElement>('campo-controla-componentes')?.addEventListener('change', atualizarSecaoComponentes); document.querySelector('#formulario-material')?.addEventListener('submit', salvarMaterial); atualizarCamposCondicionais(); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
