import type { Manutencao, TipoManutencao } from '../../../modelos/manutencao';
import { adicionarManutencao } from '../../../repositorios/repositorio-manutencoes';
import { atualizarMaterial, listarMateriais } from '../../../repositorios/repositorio-materiais';
import { listarUsuarios } from '../../../repositorios/repositorio-usuarios';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { gerarIdentificador } from '../../../utilitarios/gerador-identificador';

function campo<T extends HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id: string): T | null { return document.querySelector<T>(`#${id}`); }
function valor(id: string): string { return campo<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(id)?.value ?? ''; }
function definirErro(id: string, mensagem: string): void { const elemento = document.querySelector<HTMLElement>(`#${id}`); if (elemento) elemento.textContent = mensagem; }
function validar(): boolean { const custo = valor('campo-custo-estimado') === '' ? null : Number(valor('campo-custo-estimado')); definirErro('erro-material', valor('campo-material') ? '' : 'Selecione o material.'); definirErro('erro-tipo', valor('campo-tipo') ? '' : 'Selecione o tipo da pendência.'); definirErro('erro-responsavel', valor('campo-responsavel') ? '' : 'Selecione o escotista responsável.'); definirErro('erro-descricao', valor('campo-descricao').trim() ? '' : 'Descreva o problema ou a necessidade.'); definirErro('erro-custo', custo === null || (Number.isFinite(custo) && custo > 0) ? '' : 'Quando informado, o custo deve ser maior que zero.'); return !['erro-material', 'erro-tipo', 'erro-responsavel', 'erro-descricao', 'erro-custo'].some((id) => document.querySelector(`#${id}`)?.textContent); }
function salvar(evento: Event): void { evento.preventDefault(); if (!validar()) { definirErro('erro-geral', 'Corrija os campos indicados.'); return; } const tipo = valor('campo-tipo') as TipoManutencao; const manutencao: Manutencao = { id: gerarIdentificador('manutencao'), materialId: valor('campo-material'), atividadeId: null, tipo, descricaoProblema: valor('campo-descricao').trim(), responsavelId: valor('campo-responsavel'), dataAbertura: new Date().toISOString(), dataConclusao: null, custoEstimado: valor('campo-custo-estimado') === '' ? null : Number(valor('campo-custo-estimado')), custoReal: null, situacao: 'pendente', resultado: null, observacoes: valor('campo-observacoes').trim() }; adicionarManutencao(manutencao); const material = listarMateriais().find((item) => item.id === manutencao.materialId); if (material) atualizarMaterial({ ...material, estado: tipo === 'limpeza' ? 'aguardando_limpeza' : tipo === 'secagem' ? 'aguardando_secagem' : 'em_manutencao' }); window.location.href = `../manutencao-detalhes/index.html?id=${encodeURIComponent(manutencao.id)}`; }
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Adicionar Pendência')) return; listarMateriais().filter((material) => material.estado !== 'baixado').forEach((material) => { const opcao = document.createElement('option'); opcao.value = material.id; opcao.textContent = `${material.nome} (${material.quantidadeTotal} ${material.unidadeMedida})`; campo<HTMLSelectElement>('campo-material')?.append(opcao); }); listarUsuarios().filter((usuario) => usuario.perfil === 'escotista' && usuario.situacao === 'ativo').forEach((usuario) => { const opcao = document.createElement('option'); opcao.value = usuario.id; opcao.textContent = usuario.nomeCompleto; campo<HTMLSelectElement>('campo-responsavel')?.append(opcao); }); document.querySelector('#formulario-manutencao')?.addEventListener('submit', salvar); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
