import type { ItemKit } from '../../../modelos/item-kit'; import type { Kit, TipoKit } from '../../../modelos/kit';
import { buscarMaterialPorId, listarMateriais } from '../../../repositorios/repositorio-materiais'; import { listarPatrulhasPorSecao, buscarPatrulhaPorId } from '../../../repositorios/repositorio-patrulhas'; import { listarSecoes } from '../../../repositorios/repositorio-secoes'; import { adicionarKit, atualizarKit, buscarKitPorId, listarItensDoKit, salvarItensDoKit } from '../../../repositorios/repositorio-kits'; import { calcularQuantidadeDisponivel } from '../../../servicos/servico-disponibilidade'; import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa'; import { gerarIdentificador } from '../../../utilitarios/gerador-identificador'; import { obterParametro } from '../../../utilitarios/manipulador-url';

const campoNome = document.querySelector<HTMLInputElement>('#campo-nome'); const campoTipo = document.querySelector<HTMLSelectElement>('#campo-tipo'); const campoSecao = document.querySelector<HTMLSelectElement>('#campo-secao'); const campoPatrulha = document.querySelector<HTMLSelectElement>('#campo-patrulha'); const campoObservacoes = document.querySelector<HTMLTextAreaElement>('#campo-observacoes'); const campoMaterial = document.querySelector<HTMLSelectElement>('#campo-material'); const campoQuantidade = document.querySelector<HTMLInputElement>('#campo-quantidade'); let kitEmEdicao: Kit | null = null; let itens: ItemKit[] = [];
function definirErro(id: string, mensagem: string): void { const elemento = document.querySelector<HTMLElement>(`#${id}`); if (elemento) elemento.textContent = mensagem; }
function renderizarPatrulhas(selecionada = ''): void { if (!campoPatrulha) return; campoPatrulha.replaceChildren(); const vazia = document.createElement('option'); vazia.value = ''; vazia.textContent = 'Não informada'; campoPatrulha.append(vazia); listarPatrulhasPorSecao(campoSecao?.value ?? '').forEach((patrulha) => { const opcao = document.createElement('option'); opcao.value = patrulha.id; opcao.textContent = patrulha.nome; opcao.selected = patrulha.id === selecionada; campoPatrulha.append(opcao); }); }
function renderizarItens(): void { const lista = document.querySelector<HTMLElement>('#lista-itens'); lista?.replaceChildren(); itens.forEach((item) => { const linha = document.createElement('article'); linha.className = 'kit-formulario__item'; const nome = document.createElement('span'); nome.textContent = buscarMaterialPorId(item.materialId)?.nome ?? 'Material não encontrado'; const quantidade = document.createElement('input'); quantidade.type = 'number'; quantidade.min = '1'; quantidade.step = '1'; quantidade.value = String(item.quantidadeNecessaria); quantidade.setAttribute('aria-label', `Quantidade necessária de ${nome.textContent}`); quantidade.addEventListener('change', () => { item.quantidadeNecessaria = Math.max(1, Number(quantidade.value) || 1); renderizarResumo(); }); const remover = document.createElement('button'); remover.type = 'button'; remover.textContent = '×'; remover.setAttribute('aria-label', `Remover ${nome.textContent}`); remover.addEventListener('click', () => { itens = itens.filter((atual) => atual.id !== item.id); renderizarItens(); }); linha.append(nome, quantidade, remover); lista?.append(linha); }); renderizarResumo(); }
function renderizarResumo(): void { const resumo = document.querySelector<HTMLElement>('#resumo-kit'); if (!resumo) return; if (itens.length === 0) resumo.textContent = 'Nenhum material adicionado.'; else { const itensAtendidos = itens.filter((item) => calcularQuantidadeDisponivel(item.materialId) >= item.quantidadeNecessaria).length; const percentual = Math.round((itensAtendidos / itens.length) * 100); resumo.textContent = `${itens.length} material(is) · ${percentual}% atendido(s) pela disponibilidade atual.`; } }
function adicionarMaterial(): void { if (!campoMaterial || !campoQuantidade) return; const quantidade = Number(campoQuantidade.value); if (!campoMaterial.value || !Number.isFinite(quantidade) || quantidade <= 0) { definirErro('erro-material', 'Selecione o material e informe uma quantidade maior que zero.'); return; } definirErro('erro-material', ''); const existente = itens.find((item) => item.materialId === campoMaterial.value); if (existente) existente.quantidadeNecessaria = quantidade; else itens.push({ id: gerarIdentificador('item-kit'), kitId: kitEmEdicao?.id ?? '', materialId: campoMaterial.value, quantidadeNecessaria: quantidade }); renderizarItens(); }
function validarFormulario(): boolean { definirErro('erro-nome', campoNome?.value.trim() ? '' : 'Informe o nome do kit.'); const patrulha = buscarPatrulhaPorId(campoPatrulha?.value || null); definirErro('erro-patrulha', !patrulha || patrulha.secaoId === campoSecao?.value ? '' : 'A patrulha deve pertencer à seção.'); definirErro('erro-material', itens.length > 0 ? '' : 'Adicione pelo menos um material.'); return !['erro-nome', 'erro-patrulha', 'erro-material'].some((id) => document.querySelector(`#${id}`)?.textContent); }
function salvarKit(evento: Event): void { evento.preventDefault(); if (!validarFormulario() || !campoNome || !campoTipo || !campoSecao || !campoPatrulha || !campoObservacoes) { definirErro('erro-geral', 'Corrija os campos indicados.'); return; } const id = kitEmEdicao?.id ?? gerarIdentificador('kit'); const kit: Kit = { id, nome: campoNome.value.trim(), tipo: campoTipo.value as TipoKit, secaoId: campoSecao.value || null, patrulhaId: campoPatrulha.value || null, situacao: kitEmEdicao?.situacao ?? 'disponivel', observacoes: campoObservacoes.value.trim(), dataCadastro: kitEmEdicao?.dataCadastro ?? new Date().toISOString() }; if (kitEmEdicao) atualizarKit(kit); else adicionarKit(kit); salvarItensDoKit(id, itens.map((item) => ({ ...item, kitId: id }))); window.location.href = `../kit-detalhes/index.html?id=${encodeURIComponent(id)}&salvo=1`; }
function carregarEdicao(): void { const id = obterParametro('id'); if (!id) return; kitEmEdicao = buscarKitPorId(id); if (!kitEmEdicao) { definirErro('erro-geral', 'Kit não encontrado.'); return; } const titulo = document.querySelector<HTMLElement>('#titulo-formulario'); if (titulo) titulo.textContent = 'Editar kit'; if (campoNome) campoNome.value = kitEmEdicao.nome; if (campoTipo) campoTipo.value = kitEmEdicao.tipo; if (campoSecao) campoSecao.value = kitEmEdicao.secaoId ?? ''; if (campoObservacoes) campoObservacoes.value = kitEmEdicao.observacoes; renderizarPatrulhas(kitEmEdicao.patrulhaId ?? ''); itens = listarItensDoKit(id); }
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Cadastro de Kit')) return; listarSecoes().forEach((secao) => { const opcao = document.createElement('option'); opcao.value = secao.id; opcao.textContent = secao.nome; campoSecao?.append(opcao); }); listarMateriais().filter((material) => material.estado !== 'baixado').forEach((material) => { const opcao = document.createElement('option'); opcao.value = material.id; opcao.textContent = material.nome; campoMaterial?.append(opcao); }); carregarEdicao(); renderizarPatrulhas(kitEmEdicao?.patrulhaId ?? ''); renderizarItens(); campoSecao?.addEventListener('change', () => renderizarPatrulhas()); document.querySelector('#botao-adicionar-material')?.addEventListener('click', adicionarMaterial); document.querySelector('#formulario-kit')?.addEventListener('submit', salvarKit); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
