import { criarIndicadorSituacao } from '../../../componentes/indicador-situacao/indicador-situacao';
import { mostrarMensagem } from '../../../componentes/mensagem-retorno/mensagem-retorno';
import { solicitarConfirmacao } from '../../../componentes/modal-confirmacao/modal-confirmacao';
import type { Material } from '../../../modelos/material';
import { buscarCategoriaPorId, listarCategorias } from '../../../repositorios/repositorio-categorias';
import { buscarLocalizacaoPorId, listarLocalizacoes } from '../../../repositorios/repositorio-localizacoes';
import { baixarMaterial, listarMateriais } from '../../../repositorios/repositorio-materiais';
import { buscarSecaoPorId, listarSecoes } from '../../../repositorios/repositorio-secoes';
import { calcularQuantidadeDisponivel } from '../../../servicos/servico-disponibilidade';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { normalizarTexto } from '../../../utilitarios/normalizador-texto';

function criarCartao(material: Material): HTMLElement {
  const artigo = document.createElement('article'); artigo.className = 'materiais-listagem__cartao';
  const topo = document.createElement('header'); const titulo = document.createElement('h3'); titulo.className = 'materiais-listagem__nome'; titulo.textContent = material.nome; const codigo = document.createElement('small'); codigo.className = 'materiais-listagem__codigo'; codigo.textContent = material.codigoPatrimonio || 'Sem código'; titulo.append(codigo); topo.append(titulo, criarIndicadorSituacao(material.estado));
  const dados = document.createElement('dl'); dados.className = 'materiais-listagem__dados'; const valores: Array<[string, string]> = [['Categoria', buscarCategoriaPorId(material.categoriaId)?.nome ?? 'Não encontrada'], ['Seção', buscarSecaoPorId(material.secaoId)?.nome ?? 'Uso geral'], ['Localização', buscarLocalizacaoPorId(material.localizacaoId)?.nome ?? 'Não encontrada'], ['Quantidade', `${material.quantidadeTotal} total · ${calcularQuantidadeDisponivel(material.id)} disponível`]];
  valores.forEach(([rotulo, valor]) => { const grupo = document.createElement('div'); const termo = document.createElement('dt'); termo.textContent = rotulo; const descricao = document.createElement('dd'); descricao.textContent = valor; grupo.append(termo, descricao); dados.append(grupo); });
  const acoes = document.createElement('footer'); acoes.className = 'materiais-listagem__acoes'; const ver = document.createElement('a'); ver.href = `../material-detalhes/index.html?id=${encodeURIComponent(material.id)}`; ver.textContent = 'Visualizar'; const editar = document.createElement('a'); editar.href = `../material-formulario/index.html?id=${encodeURIComponent(material.id)}`; editar.textContent = 'Editar'; const baixar = document.createElement('button'); baixar.type = 'button'; baixar.disabled = material.estado === 'baixado'; baixar.textContent = material.estado === 'baixado' ? 'Baixado' : 'Dar baixa'; baixar.addEventListener('click', () => void confirmarBaixa(material)); acoes.append(ver, editar, baixar); artigo.append(topo, dados, acoes); return artigo;
}
async function confirmarBaixa(material: Material): Promise<void> { const confirmado = await solicitarConfirmacao('Dar baixa no material?', `${material.nome} continuará no histórico e deixará de contar como disponível.`, 'Dar baixa'); if (!confirmado) { mostrarMensagem('Ação cancelada.', 'informacao'); return; } baixarMaterial(material.id); mostrarMensagem('Material baixado com sucesso.', 'sucesso'); renderizarLista(); }
function obterValor(id: string): string { return document.querySelector<HTMLInputElement | HTMLSelectElement>(`#${id}`)?.value ?? ''; }
function renderizarLista(): void {
  const termo = normalizarTexto(obterValor('filtro-pesquisa')); const categoria = obterValor('filtro-categoria'); const secao = obterValor('filtro-secao'); const localizacao = obterValor('filtro-localizacao'); const estado = obterValor('filtro-estado'); const origem = obterValor('filtro-origem');
  const materiais = listarMateriais().filter((material) => normalizarTexto(`${material.nome} ${material.codigoPatrimonio}`).includes(termo) && (!categoria || material.categoriaId === categoria) && (!secao || (secao === 'sem-secao' ? material.secaoId === null : material.secaoId === secao)) && (!localizacao || material.localizacaoId === localizacao) && (!estado || material.estado === estado) && (!origem || material.origem === origem));
  const lista = document.querySelector<HTMLElement>('#lista-materiais'); lista?.replaceChildren(); if (materiais.length === 0) { const vazio = document.createElement('p'); vazio.className = 'materiais-listagem__vazio'; vazio.textContent = 'Nenhum material encontrado. Ajuste os filtros ou cadastre o primeiro material do grupo.'; lista?.append(vazio); } else materiais.forEach((material) => lista?.append(criarCartao(material))); const resumo = document.querySelector<HTMLElement>('#resumo-materiais'); if (resumo) resumo.textContent = `${materiais.length} material(is) encontrado(s).`;
}
function preencherFiltro(id: string, valores: Array<{ id: string; nome: string }>): void { const campo = document.querySelector<HTMLSelectElement>(`#${id}`); valores.forEach((valor) => { const opcao = document.createElement('option'); opcao.value = valor.id; opcao.textContent = valor.nome; campo?.append(opcao); }); }
function inicializarPagina(): void { if (!inicializarPaginaAdministrativa('Materiais e Equipamentos')) return; preencherFiltro('filtro-categoria', listarCategorias()); preencherFiltro('filtro-secao', listarSecoes()); preencherFiltro('filtro-localizacao', listarLocalizacoes()); document.querySelectorAll<HTMLInputElement | HTMLSelectElement>('.materiais-listagem__filtros input, .materiais-listagem__filtros select').forEach((campo) => campo.addEventListener('input', renderizarLista)); renderizarLista(); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
