import { criarIndicadorSituacao } from '../../../componentes/indicador-situacao/indicador-situacao';
import { mostrarMensagem } from '../../../componentes/mensagem-retorno/mensagem-retorno';
import { solicitarConfirmacao } from '../../../componentes/modal-confirmacao/modal-confirmacao';
import type { Material } from '../../../modelos/material';
import type { Usuario } from '../../../modelos/usuario';
import { listarAtividades, listarItensAtividades } from '../../../repositorios/repositorio-atividades';
import { buscarCategoriaPorId } from '../../../repositorios/repositorio-categorias';
import { listarComponentesPorMaterial } from '../../../repositorios/repositorio-componentes';
import { listarItensKits, listarKits } from '../../../repositorios/repositorio-kits';
import { buscarLocalizacaoPorId } from '../../../repositorios/repositorio-localizacoes';
import { listarManutencoes } from '../../../repositorios/repositorio-manutencoes';
import { baixarMaterial, buscarMaterialPorId } from '../../../repositorios/repositorio-materiais';
import { adicionarMovimentacao, listarMovimentacoesPorMaterial } from '../../../repositorios/repositorio-movimentacoes';
import { buscarSecaoPorId } from '../../../repositorios/repositorio-secoes';
import { calcularQuantidadeDisponivel } from '../../../servicos/servico-disponibilidade';
import { inicializarPaginaAdministrativa } from '../../../servicos/servico-pagina-administrativa';
import { formatarData, formatarDataHora, formatarValor } from '../../../utilitarios/formatador-data';
import { gerarIdentificador } from '../../../utilitarios/gerador-identificador';
import { obterParametro } from '../../../utilitarios/manipulador-url';
import { textoSituacao } from '../../../utilitarios/criador-html';

let materialAtual: Material | null = null; let usuarioLogado: Usuario | null = null;
function adicionarDado(lista: HTMLDListElement, rotulo: string, valor: string): void { const grupo = document.createElement('div'); const termo = document.createElement('dt'); termo.textContent = rotulo; const descricao = document.createElement('dd'); descricao.textContent = valor; grupo.append(termo, descricao); lista.append(grupo); }
function criarSecao(titulo: string, itens: string[]): HTMLElement { const secao = document.createElement('section'); secao.className = 'material-detalhes__secao'; const cabecalho = document.createElement('h3'); cabecalho.textContent = titulo; secao.append(cabecalho); if (itens.length === 0) { const vazio = document.createElement('p'); vazio.className = 'material-detalhes__vazio'; vazio.textContent = `Nenhum registro em ${titulo.toLocaleLowerCase('pt-BR')}.`; secao.append(vazio); } else { const lista = document.createElement('ul'); lista.className = 'material-detalhes__lista'; itens.forEach((texto) => { const item = document.createElement('li'); item.textContent = texto; lista.append(item); }); secao.append(lista); } return secao; }
async function darBaixa(): Promise<void> { if (!materialAtual || !usuarioLogado) return; const confirmado = await solicitarConfirmacao('Dar baixa no material?', 'O registro permanecerá no histórico, mas não contará mais como disponível.', 'Dar baixa'); if (!confirmado) { mostrarMensagem('Ação cancelada.', 'informacao'); return; } baixarMaterial(materialAtual.id); adicionarMovimentacao({ id: gerarIdentificador('movimentacao'), materialId: materialAtual.id, atividadeId: null, tipo: 'baixa', quantidade: materialAtual.quantidadeTotal, responsavelId: usuarioLogado.id, data: new Date().toISOString(), estadoRegistrado: 'baixado', observacoes: 'Baixa administrativa do material.' }); materialAtual = buscarMaterialPorId(materialAtual.id); renderizarDetalhes(); mostrarMensagem('Material baixado com sucesso.', 'sucesso'); }
function renderizarDetalhes(): void {
  const area = document.querySelector<HTMLElement>('#detalhes-material'); const relacionamentos = document.querySelector<HTMLElement>('#relacionamentos-material'); if (!area || !relacionamentos) return; area.replaceChildren(); relacionamentos.replaceChildren(); if (!materialAtual) { const vazio = document.createElement('p'); vazio.className = 'material-detalhes__vazio'; vazio.textContent = 'Material não encontrado. Volte à listagem.'; area.append(vazio); return; }
  const topo = document.createElement('header'); topo.className = 'material-detalhes__topo'; const titulo = document.createElement('h2'); titulo.className = 'material-detalhes__titulo'; titulo.textContent = materialAtual.nome; const codigo = document.createElement('small'); codigo.className = 'material-detalhes__codigo'; codigo.textContent = materialAtual.codigoPatrimonio || 'Sem código de patrimônio'; titulo.append(codigo); topo.append(titulo, criarIndicadorSituacao(materialAtual.estado)); const disponibilidade = document.createElement('p'); disponibilidade.className = 'material-detalhes__disponibilidade'; const numero = document.createElement('strong'); numero.textContent = String(calcularQuantidadeDisponivel(materialAtual.id)); disponibilidade.append(numero, document.createTextNode(` ${materialAtual.unidadeMedida}(s) disponível(is) de ${materialAtual.quantidadeTotal}.`));
  const dados = document.createElement('dl'); dados.className = 'material-detalhes__dados'; const valores: Array<[string, string]> = [['Descrição', materialAtual.descricao || 'Não informada'], ['Tipo', textoSituacao(materialAtual.tipo)], ['Categoria', buscarCategoriaPorId(materialAtual.categoriaId)?.nome ?? 'Não encontrada'], ['Seção', buscarSecaoPorId(materialAtual.secaoId)?.nome ?? 'Uso geral'], ['Localização', buscarLocalizacaoPorId(materialAtual.localizacaoId)?.nome ?? 'Não encontrada'], ['Quantidade mínima', String(materialAtual.quantidadeMinimaDesejada)], ['Origem', textoSituacao(materialAtual.origem)], ['Valor unitário', formatarValor(materialAtual.valorUnitario)], ['Data de aquisição', formatarData(materialAtual.dataAquisicao)], ['Capacidade', materialAtual.capacidadePessoas === null ? 'Não se aplica' : `${materialAtual.capacidadePessoas} pessoas`], ['Comprimento', materialAtual.comprimentoMetros === null ? 'Não se aplica' : `${materialAtual.comprimentoMetros} m`], ['Restrição de uso', materialAtual.restricaoUso ?? 'Nenhuma'], ['Observações', materialAtual.observacoes || 'Nenhuma'], ['Cadastro', formatarData(materialAtual.dataCadastro)]]; valores.forEach(([rotulo, valor]) => adicionarDado(dados, rotulo, valor));
  const acoes = document.createElement('footer'); acoes.className = 'material-detalhes__acoes'; const editar = document.createElement('a'); editar.href = `../material-formulario/index.html?id=${encodeURIComponent(materialAtual.id)}`; editar.textContent = 'Editar material'; const baixar = document.createElement('button'); baixar.type = 'button'; baixar.textContent = materialAtual.estado === 'baixado' ? 'Material baixado' : 'Dar baixa'; baixar.disabled = materialAtual.estado === 'baixado'; baixar.addEventListener('click', () => void darBaixa()); acoes.append(editar, baixar); area.append(topo, disponibilidade, dados, acoes);
  const componentes = listarComponentesPorMaterial(materialAtual.id).map((componente) => `${componente.nome}: ${componente.quantidadeEncontrada}/${componente.quantidadeEsperada} · ${textoSituacao(componente.estado)}`); const itensKits = listarItensKits().filter((item) => item.materialId === materialAtual?.id); const kits = itensKits.map((item) => `${listarKits().find((kit) => kit.id === item.kitId)?.nome ?? 'Kit não encontrado'} · ${item.quantidadeNecessaria} necessário(s)`); const itensAtividades = listarItensAtividades().filter((item) => item.materialId === materialAtual?.id); const atividades = itensAtividades.map((item) => `${listarAtividades().find((atividade) => atividade.id === item.atividadeId)?.nome ?? 'Atividade não encontrada'} · ${textoSituacao(item.situacao)}`); const manutencoes = listarManutencoes().filter((manutencao) => manutencao.materialId === materialAtual?.id).map((manutencao) => `${textoSituacao(manutencao.tipo)} · ${textoSituacao(manutencao.situacao)} · ${manutencao.descricaoProblema}`); const movimentacoes = listarMovimentacoesPorMaterial(materialAtual.id).sort((a, b) => b.data.localeCompare(a.data)).slice(0, 5).map((movimentacao) => `${textoSituacao(movimentacao.tipo)} · ${movimentacao.quantidade} · ${formatarDataHora(movimentacao.data)}`); relacionamentos.append(criarSecao('Componentes', componentes), criarSecao('Kits', kits), criarSecao('Atividades relacionadas', atividades), criarSecao('Manutenções', manutencoes), criarSecao('Últimas movimentações', movimentacoes));
}
function inicializarPagina(): void { usuarioLogado = inicializarPaginaAdministrativa('Detalhes do Material'); if (!usuarioLogado) return; const id = obterParametro('id'); materialAtual = id ? buscarMaterialPorId(id) : null; renderizarDetalhes(); if (obterParametro('salvo') === '1') mostrarMensagem('Material salvo com sucesso.', 'sucesso'); }
document.addEventListener('DOMContentLoaded', inicializarPagina);
